title: Synobsys standards and guidelines
author: Synobsys
email: info@synobsys.nl
description: > # this means to ignore newlines until "baseurl:"
  standards, best practices and how-tos for developing OutSystems applications
# social links
twitter_username: synobsys # DO NOT include the @ character, or else the build will fail!
github_username:  synobsys # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one